name: ggnet
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - pytorch-cuda
  - pyg
  - pytorch-scatter
  - pytorch-sparse
  - pip
  - pip:
      - einops
      - hydra-core
      - lightning
      - numpy>1.20.3
      - omegaconf
      - pandas>=1.4
      - PyYAML
      - scikit-learn
      - scipy
      - tables
      - torchmetrics>=0.7
      - tqdm
      - wandb
      - openpyxl
